#!/bin/sh

/usr/bin/logger -t "POST-MOUNT" "Mounted device $1"

# If ASUS drive was mounted
if [ "$1" = "/tmp/mnt/ASUS" ]
then
    # Create backup directories if not exists
    if [ ! -d "$1/backup" ]
    then
        /usr/bin/logger -t "POST-MOUNT" "Creating directory $1/backup"
        /bin/mkdir "$1/backup"
    fi
    if [ ! -d "$1/archive" ]
    then
        /usr/bin/logger -t "POST-MOUNT" "Creating directory $1/archive"
        /bin/mkdir "$1/archive"
    fi
    if [ ! -d "$1/archive/weekly" ]
    then
        /usr/bin/logger -t "POST-MOUNT" "Creating directory $1/archive/weekly"
        /bin/mkdir "$1/archive/weekly"
    fi


    # If drive was in a missing state then set it to FAIL
    # if no backup created in two days, otherwise set to SUCCESS
    if [ "$(/bin/nvram get ecrs_backup_usb_status)" -eq "2" ]
    then
        if [ "$(/usr/bin/find /tmp/mnt/ASUS/archive -mtime -2 | /usr/bin/wc -l)" -gt "0" ]
        then
            /bin/nvram set ecrs_backup_usb_status=0
            /bin/nvram set ecrs_backup_usb_text=""
        else
            /bin/nvram set ecrs_backup_usb_status=1
            /bin/nvram set ecrs_backup_usb_text=""
        fi

        /bin/nvram commit
    fi


    # Add/replace cron job for USB backup
    /usr/sbin/cru d USBBackup
    /usr/sbin/cru a USBBackup "0 20 * * * /jffs/nvram-save/backup.sh"
fi
