--- /home/asus/asuswrt-merlin/release/src/router/rom/Makefile	2017-01-03 15:41:08.258608576 -0500
+++ /home/asus/asuswrt-merlin/release/ecrs/router/rom/mods/Makefile	2017-01-03 15:32:36.878597073 -0500
@@ -192,3 +192,11 @@
 
 	install -m 0755 webs_scripts/GoogleDNS_Update.sh $(INSTALLDIR)/usr/sbin
 
+#	ECRS mod to load prebuilt configs and scripts
+	echo -e "Adding default configs and scripts to rom"
+	mkdir -p $(INSTALLDIR)/rom/configs
+	mkdir -p $(INSTALLDIR)/rom/scripts
+	mkdir -p $(INSTALLDIR)/rom/nvram-save
+	cp -rfv configs/* $(INSTALLDIR)/rom/configs
+	cp -rfv scripts/* $(INSTALLDIR)/rom/scripts
+	cp -rfv nvram-save/* $(INSTALLDIR)/rom/nvram-save
